In [3]:
### Codigo de lectura de mallas con meshio
import numpy as np
import meshio
mesh = meshio.read("gato.obj")
points = mesh.points
tris = []
quads = []
for cells in mesh.cells:
    if cells.type == 'triangle':
        tris.extend( cells.data )
    elif cells.type == 'quad':
        quads.extend( cells.data )
    else:
        raise Exception("Elemento err´oneo")

t=0
for i in quads:
    a = quads[t][0]
    b = quads[t][1]
    c = quads[t][2]
    d = quads[t][3]
    triangle = [a , b, c]
    triangle1 = [c, d, a]
    tris.append(triangle)
    t = t + 1

tris = np.array(tris)
print(tris[0:5])
tris.shape

area = np.array([points[tris[0],[1]]-points[tris[0],[0]],points[tris[0],[1]]-points[tris[0],[0]],points[tris[0],[1]]-points[tris[0],[0]]])
det = np.linalg.det(area)
A = area/2
print(A)

# Ahora definimos una función para cualquier Triangulo
def volp(p0,p1,p2):
    v1 = p1 - p0
    v2 = p2 - p0
    v_cross = np.cross(v1, v2)
    area = np.linalg.norm(v_cross)/2
    return area

#Ahora sumamos todos los triangulos para Calcular el area superficial 
A = 0
for i in range(tris.shape[0]):
    triangulo = tris[i]
    p0 = points[triangulo[0]]
    p1 = points[triangulo[1]]
    p2 = points[triangulo[2]]
    A = A + volp(p0,p1,p2)
print(A, "cm\xb2")

[[51801 51802 51800]
 [51801 51803 51802]
 [51801 51804 51803]
 [51801 51800 51804]
 [51818 51819 51817]]
[[111.21715307 110.04766654 110.03262091]
 [111.21715307 110.04766654 110.03262091]
 [111.21715307 110.04766654 110.03262091]]
39420.434728831926 cm²
